server:
  port: 9001
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: cookie
    password: 1234

#mybatis:
#  config-location: classpath:config/mybatis-config.xml
#  mapper-locations: classpath:mapper/**/*.xml
